name: PvP_Toggle
version: 1.0.0
author: John_Willikers
main: com.johnwillikers.pvp.PvpToggle
commands:
  pvp:
    description: Toggle PvP
    aliases: [pvptoggle]
    permissions: pvp.toggle
    permission-message: &cYou do not have permission to do that!
  setpvp:
    description: Force toggle pvp
    aliases: [forcepvp, forcepvptoggle, pvpadmin]
    permissions: pvp.toggle.force
    permission-message: &cYou do not have permission to do that!